#!/bin/sh -e

. ../lib

getDependencies() {
    printf "%b\n" "${CYAN}Installing dynamic window manager...${RC}"
    yay -S --noconfirm --needed git base-devel xorg-server xorg-xrandr xorg-xinit alacritty rofi thunar gvfs flameshot feh dunst mate-polkit picom-ftlabs-git ttf-meslo-nerd noto-fonts noto-fonts-emoji papirus-icon-theme 
}

setupDwmGab() {
    GH_DIR="$HOME/github"

    if [ ! -d "${GH_DIR}" ]; then
        mkdir -p "${GH_DIR}"
    fi

    cd "${GH_DIR}" && git clone https://github.com/dallagnoli/dwm.git 
    cd dwm && sudo make clean install
    ln -sf "${PWD}"/alacritty "${HOME}"/.config/alacritty
    ln -sf "${PWD}"/rofi "${HOME}"/.config/rofi
    cd slstatus && sudo make clean install
}

setupBackground() {
    BKG_DIR="$HOME/media/images/background"

    if [ ! -d "${BKG_DIR}" ]; then
        mkdir -p "${BKG_DIR}"
    fi

    cd "${BKG_DIR}" && git clone https://github.com/dallagnoli/bkg.git .
}

setupDisplayManager() {
    XRC="$HOME/.xinitrc"
    printf "exec dwm\n" > "${XRC}"
}

getDependencies
setupDwmGab
setupBackground
setupDisplayManager